# File: charting-app/templates/fastapi-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fastapi
  labels:
    app: fastapi
spec:
  replicas: {{ .Values.fastapi.replicaCount }}
  selector:
    matchLabels:
      app: fastapi
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: fastapi
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.fastapi.image.repository }}:{{ .Values.fastapi.image.tag }}"
          imagePullPolicy: {{ .Values.fastapi.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.fastapi.service.port }}
